<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ALVIS" ignored="0" name="Test" tests="10" failures="3" timestamp="03 Feb 2020 13:33:26 GMT" time="9.433" errors="0">
  <testcase name="tc001" time="0.011" classname="org.failed.TestFailed"/>
  <testcase name="tc002" time="0.006" classname="org.failed.TestFailed"/>
  <testcase name="tc003" time="0.002" classname="org.failed.TestFailed">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at org.failed.TestFailed.tc003(TestFailed.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- tc003 -->
  <testcase name="tc004" time="0.007" classname="org.failed.TestFailed">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at org.failed.TestFailed.tc004(TestFailed.java:38)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- tc004 -->
  <testcase name="tc005" time="0.002" classname="org.failed.TestFailed"/>
  <testcase name="tc006" time="0.002" classname="org.failed.TestFailed"/>
  <testcase name="tc007" time="0.001" classname="org.failed.TestFailed">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at org.failed.TestFailed.tc007(TestFailed.java:53)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- tc007 -->
  <testcase name="tc008" time="0.001" classname="org.failed.TestFailed"/>
  <testcase name="tc009" time="0.004" classname="org.failed.TestFailed"/>
  <testcase name="tc010" time="0.001" classname="org.failed.TestFailed"/>
</testsuite> <!-- Test -->
